language: python
python:
  - "3.5"
install:
  - pip install coverage
  - pip install -r requirements.txt
script:
  - coverage run manage.py test
  - coverage report --skip-covered
after_success:
  - coveralls
